packages: []
allowBuilds:
  aws-sdk: true
  dtrace-provider: true
  pre-commit: true
  snyk: true
  spawn-sync: true
  sqlite3: true
  better-sqlite3: true
  
# disable minimum release age to allow immediate releases
minimumReleaseAge: 0